language: python
python:
- '2.7'
before_script:
- yes | python setup.py install
- git clone https://github.com/uc-cdis/dictionaryutils; cd dictionaryutils; git checkout feat/version
script:
- ./run_tests.sh
deploy:
  provider: s3
  access_key_id: AKIAINXLWNMMDOPKHNRA
  secret_access_key:
    secure: vVjYxjaxCi9KIpi8/ov8o91bVJy3gCMvL7SHxHiX/S0ufx9/JcGB41Uvpa3My5z7+EJBH+KBOfiDtwHmv0SDr4K+QcwvMwq+KAlCpWCMJorOVwMywQ9Bwl4MgAs6f+jKjKyK4uY+aC+juz4hza+PBddDrDKqLDHrpgJ0YPwkamLuqHuhbHrLr2MnTHY1UoktHSxfLma7lsOPThI7bNJYM1tLcJ9YZw2O907ZK/RpG89dZ8TfzbXfFQ7KG0SZ8PmX5VEPPbbyUFDepQpXslVeh6VYTsv9XeSNpKhmVO107iBBp7T5ID2q5whLnXAcRJP4oDJilnm5TJbX7U4RgJk9OqCbzYeG75FxKEyLZpBrHpEl/HYOl+PfHmzWGA/3FAL4AXeHamXax95BXuLd2dHItfRs+lNLlq6lh/v/pbSfK6miMRaP/U7wtW9gi8FffzEJnpxNgY0X3GxlsDQQtbCgIVK9yIH5yII+V7+3RdFMIppC7221x1746e91M0EQRliRXaTx6iHr3st6hF9ZZZiUL8wurICSC00GWa76sXCxKHueh7WMFQCssGpDd1IuR/1yVlPRDgCJHvMJctHmWX7IdUWrfPJu2CRMY2ZskKIWeUspzGYhk9Ygf/14PB3jUQmM1vh5WZAu7OSigkZ22N3SwFiFHl2U4/GjHTsfy6DCS/Y=
  bucket: dictionary-artifacts
  local-dir: artifacts
  upload-dir: envdictionary/$TRAVIS_BRANCH
  skip_cleanup: true
  on:
    repo: occ-data/envdictionary
    all_branches: true
